// src/delegacias.js
import { appState, normalizeText } from './state.js';
import { syncDocToFirestore, fetchCollection } from './db.js';

export async function initDelegaciasModule() {
  appState.delegacias = await fetchCollection('delegacias');

  // Se o banco de delegacias estiver vazio, gera automaticamente com base nos servidores
  if (appState.delegacias.length === 0 && appState.servidores.length > 0) {
    await autoGenerateDelegaciasFromServidores();
  }
}

async function autoGenerateDelegaciasFromServidores() {
  const mapDelegacias = new Map();

  appState.servidores.forEach(srv => {
    const delNome = srv.delegaciaId || '8ª SDP PARANAVAÍ';
    if (!mapDelegacias.has(delNome)) {
      const delId = 'del_' + normalizeText(delNome).replace(/\s+/g, '_');
      mapDelegacias.set(delNome, {
        id: delId,
        nome: delNome,
        sdpId: srv.sdpId || '8SDP',
        isConsorcio: false,
        delegaciasIds: [delId] // Array nativo para consórcios
      });
    }
  });

  for (const [_, delData] of mapDelegacias) {
    appState.delegacias.push(delData);
    await syncDocToFirestore('delegacias', delData.id, delData);
  }
  console.log(`🏢 ${mapDelegacias.size} delegacias geradas e salvas no Firestore!`);
}

export function renderDelegaciasCards(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;

  if (appState.delegacias.length === 0) {
    container.innerHTML = `<p class="p-4 text-xs text-slate-500">Nenhuma delegacia cadastrada.</p>`;
    return;
  }

  let html = `<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 p-4">`;

  appState.delegacias.forEach(del => {
    const qtdServidores = appState.servidores.filter(s => s.delegaciaId === del.nome || s.delegaciaId === del.id).length;

    html += `
      <div class="bg-slate-50 border border-slate-200 rounded-xl p-3 shadow-sm flex flex-col justify-between">
        <div>
          <div class="flex items-center justify-between mb-1">
            <span class="text-[10px] font-bold px-2 py-0.5 rounded bg-slate-200 text-slate-700 font-mono">${del.sdpId || 'SDP'}</span>
            <span class="text-[10px] font-semibold text-slate-500">${qtdServidores} Policiais</span>
          </div>
          <h3 class="font-bold text-xs text-slate-800 leading-snug">${del.nome}</h3>
        </div>
        <div class="mt-3 pt-2 border-t border-slate-200/60 flex items-center justify-between text-[10px]">
          <span class="text-slate-500">${del.isConsorcio ? '🤝 Consórcio' : '🏢 Unidade Única'}</span>
          <button onclick="window.editarDelegacia('${del.id}')" class="text-indigo-600 hover:text-indigo-800 font-bold">
            Gerenciar
          </button>
        </div>
      </div>
    `;
  });

  html += `</div>`;
  container.innerHTML = html;
}
