// src/delegacias.js
import { appState, normalizeText } from './state.js';
import { syncDocToFirestore, fetchCollection } from './db.js';
import { renderCalendarGrid } from './calendar.js';

export async function initDelegaciasModule() {
  appState.delegacias = await fetchCollection('delegacias');

  if (appState.delegacias.length === 0 && appState.servidores.length > 0) {
    await autoGenerateDelegaciasFromServidores();
  }
}

async function autoGenerateDelegaciasFromServidores() {
  const mapDelegacias = new Map();

  appState.servidores.forEach(srv => {
    const delNome = srv.delegaciaId || '8ª SDP PARANAVAÍ';
    if (!mapDelegacias.has(delNome)) {
      const delId = 'del_' + normalizeText(delNome).replace(/\s+/g, '_');
      mapDelegacias.set(delNome, {
        id: delId,
        nome: delNome,
        sdpId: srv.sdpId || '8SDP',
        isUnificado: false,
        delegaciasIds: [delId]
      });
    }
  });

  for (const [_, delData] of mapDelegacias) {
    appState.delegacias.push(delData);
    await syncDocToFirestore('delegacias', delData.id, delData);
  }
}

export function renderDelegaciasCards(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;

  if (appState.delegacias.length === 0) {
    container.innerHTML = `<p class="p-4 text-xs text-slate-500">Nenhuma delegacia cadastrada.</p>`;
    return;
  }

  let html = `<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 p-4">`;

  appState.delegacias.forEach(del => {
    const qtdServidores = appState.servidores.filter(s => s.delegaciaId === del.nome || s.delegaciaId === del.id).length;

    html += `
      <div class="bg-slate-50 border border-slate-200 rounded-xl p-3 shadow-sm flex flex-col justify-between">
        <div>
          <div class="flex items-center justify-between mb-1">
            <span class="text-[10px] font-bold px-2 py-0.5 rounded ${del.isUnificado ? 'bg-amber-100 text-amber-800' : 'bg-slate-200 text-slate-700'} font-mono">
              ${del.isUnificado ? '🔗 Plantão Unificado' : (del.sdpId || 'SDP')}
            </span>
            <span class="text-[10px] font-semibold text-slate-500">${qtdServidores} Policiais</span>
          </div>
          <h3 class="font-bold text-xs text-slate-800 leading-snug">${del.nome}</h3>
        </div>
        <div class="mt-3 pt-2 border-t border-slate-200/60 flex items-center justify-between text-[10px]">
          <button onclick="window.editarNomeDelegacia('${del.id}')" class="text-slate-600 hover:text-slate-900 font-bold">
            ✏️ Renomear
          </button>
          <button onclick="window.gerenciarUnificacao('${del.id}')" class="text-indigo-600 hover:text-indigo-800 font-bold">
            ${del.isUnificado ? 'Editar Junção' : 'Unificar Plantão'}
          </button>
        </div>
      </div>
    `;
  });

  html += `</div>`;
  container.innerHTML = html;
}

// Renomear Delegacia
window.editarNomeDelegacia = async function(delegaciaId) {
  const del = appState.delegacias.find(d => d.id === delegaciaId);
  if (!del) return;

  const novoNome = prompt("Informe o novo nome para a unidade:", del.nome);
  if (novoNome && novoNome.trim() !== "" && novoNome !== del.nome) {
    del.nome = novoNome.trim().toUpperCase();
    await syncDocToFirestore('delegacias', del.id, del);
    
    renderDelegaciasCards('delegacias-container');
    renderCalendarGrid('calendar-container');
  }
};

// Modal e Gestão de Plantão Unificado
window.gerenciarUnificacao = function(delegaciaId) {
  const del = appState.delegacias.find(d => d.id === delegaciaId);
  if (!del) return;

  const modal = document.getElementById('modal-unificacao');
  if (!modal) return;

  document.getElementById('modal-unificacao-id').value = del.id;
  document.getElementById('modal-unificacao-nome').value = del.nome;

  const containerLista = document.getElementById('modal-unificacao-lista');
  const delegaciasIndividuais = appState.delegacias.filter(d => !d.isUnificado);

  containerLista.innerHTML = delegaciasIndividuais.map(d => {
    const isChecked = del.delegaciasIds && del.delegaciasIds.includes(d.id);
    return `
      <label class="flex items-center gap-2 p-2 bg-slate-50 hover:bg-slate-100 rounded-lg cursor-pointer text-xs font-semibold text-slate-700 border">
        <input type="checkbox" value="${d.id}" ${isChecked ? 'checked' : ''} class="chk-unificacao-del rounded text-indigo-600 focus:ring-indigo-500">
        <span>${d.nome}</span>
      </label>
    `;
  }).join('');

  modal.classList.remove('hidden');
};

window.fecharModalUnificacao = function() {
  document.getElementById('modal-unificacao')?.classList.add('hidden');
};

window.salvarUnificacao = async function(e) {
  e.preventDefault();

  const delId = document.getElementById('modal-unificacao-id').value;
  const checkboxes = document.querySelectorAll('.chk-unificacao-del:checked');
  const idsSelecionados = Array.from(checkboxes).map(cb => cb.value);

  const delObj = appState.delegacias.find(d => d.id === delId);
  if (delObj) {
    delObj.isUnificado = idsSelecionados.length > 1;
    delObj.delegaciasIds = idsSelecionados.length > 0 ? idsSelecionados : [delId];

    await syncDocToFirestore('delegacias', delObj.id, delObj);
    
    window.fecharModalUnificacao();
    renderDelegaciasCards('delegacias-container');
    renderCalendarGrid('calendar-container');
    alert("Configuração salva com sucesso!");
  }
};
